kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 1
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: luisbelloch/spark
          command: ["/opt/spark/sbin/start-slave.sh", "spark://spark-master:7077"]
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "true"
          resources:
            requests:
              cpu: 100m
